name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GitHub Container Registry

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase repository name
      id: lower_repo
      run: echo "repo_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ steps.lower_repo.outputs.repo_name }}:${{ github.sha }} # Tag with commit SHA using lowercase repo name
        # Optionally, add a 'latest' tag for the main branch
        # tags: |
        #   ghcr.io/${{ steps.lower_repo.outputs.repo_name }}:${{ github.sha }}
        #   ${{ github.ref == 'refs/heads/main' && format('ghcr.io/{0}:latest', github.repository) || '' }}
